### ISSUE TITLE
do you have hevc compressorbot with fast process

### ISSUE THREAD

**Issue by sunilroy007** [1Danish-00/CompressorBot#7]
i had a repo but it takes 4 to 5 hours to compress just 300mb size file

**Comment by Mrvishal2k2** [comment]
> i had a repo but it takes 4 to 5 hours to compress just 300mb size file

Compression can become fast if you host bot in any paid server with high CPU and ram :(
If you can afford azure or any good resource 
You can get some good vps with good specs and things will happen fast

**Comment by Aanchal101** [comment]
You can use railway it's really good but there's 5 dollar limit I got bug on railway that's why my bot  never becomes down but now railway fix its bug but still you can use it for compress bot  really fast compression speed compare to heroku
Site - railway.app make sure your github account should be 30 days old
